---
- name: Pull Docker Image from Docker Hub and Run Container
  hosts: localhost
  gather_facts: no
  remote_user: nikki00011
  become: yes
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "nikki00011/spe_mini"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
      become: yes

    - name: Run Container
      docker_container:
        name: spe_mini
        image: "nikki00011/spe_mini"
        state: started
      register: docker_container_result

    - name: Display Docker Container Result
      debug:
        var: docker_container_result
